### ISSUE TITLE
Incompatibility with zend-modulemanager >2.5.1

### ISSUE THREAD

**Issue by stefanorg** [prolic/HumusMvc#4]
Hi,
with the release of zend-modulmanager 2.5.2 the type constraints changed: [LocatorRegistrationListener](https://github.com/zendframework/zend-modulemanager/blob/master/src/Listener/LocatorRegistrationListener.php#L70)

The application throw an Exception on boot.

**Comment by prolic** [comment]
Fixed. Released 1.2.0. straight away.

Make sure you have error_reporting(E_ALL & ~E_STRICT & ~E_NOTICE); in your public/index.php or in your php.ini settings, as there is no other way, we must disable strict standards.

**Comment by prolic** [comment]
Thanks for reporting ! :)

**Comment by stefanorg** [comment]
:+1:
