### ISSUE TITLE
Use  bootstrap object to access dependencies 

### ISSUE THREAD

**Issue by herbergt** [prolic/HumusMvc#5]
@prolic I have decided to use your excellent library to make the migration from ZF1 to ZF2. In the first iteration I'm trying to run the application still using the bootstrap object in the entire application for example:      $csConfig = $this->_bootstrap->getOption('customerservicephonenumber'); where the $this->_bootstrap object extends from Zend_Application_Bootstrap_Bootstrap object. Is there a way where I can gradually get rid the use of the bootstrap object and change it with the service manager?  In this post https://www.sasaprolic.com/2012/10/when-migration-to-zend-framework-2.html is mentioned that we can  instantiate the dependencies within onBootstrap function putting those within Zend_Registry, the problem is that I'm not using directly Zend_Registry to access the dependencies in the classes but the bootstrap object as I mentioned before.

Do you have any suggestion for my case? In advance thank you for your help.

**Comment by qaniel** [comment]
bump

**Comment by prolic** [comment]
Hey, sorry I did the migration away from ZF1 years ago and that's when I open sourced this tool that I used at that time. I can't remember all the details anymore and maybe today I would migrate things diferently, I don't know.
You can use this library as is and hopefully it helps you with the migration. Other than that, you can hire me as consultant to assist with the migration, but I can't invest additional spare time to remember about old ZF1 stuff.
